### ISSUE TITLE
make auth context 

### ISSUE THREAD

**Issue by tomatija** [tomatija/Menzar#44]
when the user is logged in:

do not show login or sign up pages
- give option to logout in navbar
- when no user is logged in:

show sign up and login
- hide logout

**Comment by tomatija** [comment]
when the user is logged in:
- do not show login or sign up pages
- give option to logout in navbar

when no user is logged in:
- show sign up and login
- hide logout

**Comment by tomatija** [comment]
Added navigation bar in #47, but we need to add authentication context to add the functionality listed above.

**Comment by zvaktualno** [comment]
Doing it differently
